version: "3.8"
services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP port – configure your app to send mail here
      - "8025:8025"  # Web UI – access via http://localhost:8025